### ISSUE TITLE
Encryption on save doesn't work anymore in 0.2.0

### ISSUE THREAD

**Issue by Gui13** [signageos/vscode-sops#18]
I can open a sops-encrypted file correctly, but when I save, _even though the little popup in the bottom left says that the file was encrypted_, it doesn't save it to the original file (and I don't know where it is saved..)

I appears to be a regression because this used to work. I have VSCode 1.50.1, and a friend with VSCode 1.50.0 can see it working on his end.

Any idea how I can help you debug that?

**Comment by Maarten82-bit** [comment]
We had exact the same problem, somehow we fixed it by installing node.js in your WSL (in my case Ubuntu). So, hopefully it works for you too. This was a strange problem, took us about a bloody full day.

**Comment by misak113** [comment]
Hi, sorry about that. I didn't notice any problem during my yesterday testing before release v0.2.0. I tested it on node.js version v12.16.2.
Could you please send me the versions of node.js which it didn't work and which version it works now?
The reason is probably some upgrade of dependency which stopped supporting old node.js versions.

I try to get rid of node.js requirement on the next release.
Additionally, I'd like to have a way how to canary release beta versions before I release stable one however VSCode extension environment doesn't support it yet. You can vote here ;) https://github.com/microsoft/vscode/issues/15756

**Comment by Maarten82-bit** [comment]
@misak113 , I hadn't installed jsnode in my WSL yet. I now have node.js v10.19.0 installed (works fine).

I was replicating the setup off my colleague (works for him), but we missed this one. So, that's probably a large part of the blame why we couldn't find the issue.
