### ISSUE TITLE
Extension doesn't work when file type is "helm-template"

### ISSUE THREAD

**Issue by jdomag** [signageos/vscode-sops#28]
I use tim-koehler.helm-intellisense  extension for helm and VScode recognise values.yaml as "helm-template" type of file. Sops extension seems to be not enabled then (I assume it works only for yaml file type). Would be nice to use both extensions the same time.

![image](https://user-images.githubusercontent.com/28705876/117421875-42882e00-af1f-11eb-8b6c-e6471980ff7a.png)

**Comment by misak113** [comment]
I tried to find the problem, however, I was unsuccessful.
I'm using the mentioned extension as well. But the file type of those HELM templates is detected by VSCode as standard YAML files, not the `helm-template`. Maybe it's because you are using one more extension which changes the file type to helm-template.

Additionally, the HELM templates are usually not a valid YAML files. They use a lot of template specific characters, which makes YAML file unparsable by standard tools. I guess the SOPS Mozilla tool cannot work with those invalid files as well. Tell me if I'm wrong.

So could you provide me more info on this issue? Some example files and related code extension list would be great.

**Comment by jdomag** [comment]
Hi @misak113 
Ok I see it now - the helm-template file is detected and changed by Kubernetes extension that provides helm template intellisense:
ms-kubernetes-tools.vscode-kubernetes-tools
